FIND_PATH(CEF_INCLUDE_DIR include/cef_app.h "thirdparty/cef3" NO_DEFAULT_PATH)
FIND_PATH(CEF_BINARY_DIR bin/libcef.dll "thirdparty/cef3" NO_DEFAULT_PATH)

FIND_LIBRARY(CEF_LIBRARY_DEBUG NAMES libcef.lib PATHS "thirdparty/cef3/debug/lib" NO_DEFAULT_PATH)
FIND_LIBRARY(CEF_LIBRARY_WRAPPER_DEBUG NAMES libcef_dll_wrapper.lib PATHS "thirdparty/cef3/debug/lib" NO_DEFAULT_PATH)
FIND_LIBRARY(CEF_LIBRARY_RELEASE NAMES libcef.lib PATHS "thirdparty/cef3/lib" NO_DEFAULT_PATH)
FIND_LIBRARY(CEF_LIBRARY_WRAPPER_RELEASE NAMES libcef_dll_wrapper.lib PATHS "thirdparty/cef3/lib" NO_DEFAULT_PATH)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(
	CEF
	REQUIRED_VARS 
	CEF_LIBRARY_DEBUG
	CEF_LIBRARY_RELEASE
	CEF_INCLUDE_DIR 
	CEF_BINARY_DIR
)

# show the CEF_INCLUDE_DIR and CEF_LIBRARY_DEBUG variables only in the advanced view
# MARK_AS_ADVANCED(CEF_INCLUDE_DIR CEF_LIBRARY_DEBUG)